#!/bin/sh

/bin/mount -t ext4 "/dev/vdb" /overlay
mkdir -p /overlay/root /overlay/work /overlay

/bin/mount -o noatime,lowerdir=/,upperdir=/overlay/root,workdir=/overlay/work -t overlay "overlayfs:/overlay/root" /mnt
pivot_root /mnt /mnt/rom

echo "${1}" > /etc/hostname
shift

mkdir -p /run
/bin/mount -o rw,nodev,nosuid,size=1G -t tmpfs tmpfs /run
mkdir -p /run/systemd/network/

echo "
[Match]
Name=eth0

[Address]
Address=${1}/24

[Route]
Gateway=${2}
" > /run/systemd/network/01-wired.network
shift 2

if [ "${1}" != "" ]; then
shift 2
echo "

[Address]
Address=${1}/80

[Route]
Gateway=${2}
" >> /run/systemd/network/01-wired.network
fi

cat /run/systemd/network/01-wired.network

exec /lib/systemd/systemd
